### ISSUE TITLE
Ubuntu 18.04 apt error: No module named 'flask_script'

### ISSUE THREAD

**Issue by aTanCS** [Salamek/blacklist#18]
apt fails to configure python3-blacklist package in Ubuntu 18.04:
```Setting up python3-blacklist (1.0.25-1) ...
Adding blacklist user
Traceback (most recent call last):
  File "/usr/bin/blacklist", line 11, in <module>
    load_entry_point('blacklist==1.0.25', 'console_scripts', 'blacklist')()
  File "/usr/lib/python3/dist-packages/blacklist/__main__.py", line 6, in main
    from blacklist.bin.blacklist import main as _main
  File "/usr/lib/python3/dist-packages/blacklist/bin/blacklist.py", line 70, in <module>
    from flask_script import Shell, Manager
ModuleNotFoundError: No module named 'flask_script'
dpkg: error processing package python3-blacklist (--configure):
 installed python3-blacklist package post-installation script subprocess returned error exit status 1
...
Errors were encountered while processing:
 python3-blacklist
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by aTanCS** [comment]
python3-flask-script must be a dependency for python3-blacklist. After installing flask-script there is another error. I guess it should check if user blacklist already exists.
```
Setting up python3-blacklist (1.0.25-1) ...
Adding blacklist user
useradd: user 'blacklist' already exists
dpkg: error processing package python3-blacklist (--configure):
 installed python3-blacklist package post-installation script subprocess returned error exit status 9
Errors were encountered while processing:
 python3-blacklist
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Salamek** [comment]
@aTanCS Flask-script is deprecated as of Flask 0.11...
